version: '3.8'
services:
  lab3-svc:
    hostname: lab1-svc
    networks:
      - lab
    build:
      context: .
      dockerfile: ./ProjectManagementAPI/Dockerfile
    ports:
      - 8080:8080

networks:
  lab:
    driver: bridge
