name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: SSH into instance
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@<your_instance_public_ip> << 'EOF'
          # Install Git
          sudo apt-get update
          sudo apt-get install -y git

          #Testing
          whoami

          #Test git version
          git --verion

        EOF
